# Generated by Django 5.2.8 on 2026-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcode',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
